// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deck struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	UserID      int32
	Public      pgtype.Bool
}

type User struct {
	ID            int32
	Email         string
	Password      string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
	Username      pgtype.Text
	OauthID       pgtype.Text
	OauthProvider pgtype.Text
	HasOauth      pgtype.Bool
	Avatar        pgtype.Text
	Permission    pgtype.Int4
}
