server:
  Port: 1815
  AppVersion: 1.2.1-dev
  Host: http://localhost:1815
  FrontendURL: http://localhost:3000
Database:
  DSN: postgresql://localhost:5435/postgres?user=memnix&password=memnix
Redis:
  Addr: :6379
  Password: redis
Log:
  Level: debug
Auth:
  BcryptCost: 10
  JWTSecret: a5TAHNqyUZEQEKsz4RZ7wP3f3gQz6bNGf8MgfpEimJzPXV
  JWTHeaderLen: 2
  JWTExpiration: 24
  Github:
    ClientID: d0924d1c95c46f561416
    ClientSecret: 2d04c7db9b53c1d0d26590631e757a2a01b5ae48
  Discord:
    ClientID: 665171388734111745
    ClientSecret: dz5Mxl-HraAoj0rPnFQbOzdtsPomL4l6
    URL: https://discord.com/api/oauth2/authorize?client_id=665171388734111745&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1815%2Fv2%2Fsecurity%2Fdiscord_callback&scope=email+identify
Sentry:
  DSN: https://cf8a9efc80bb44661b4edfd08d231e70@o4504718109245440.ingest.sentry.io/4505845474918400
  Environment: developement
  Debug: false
  Release: memnix@1.2.1-dev
  TracesSampleRate: 1.0
  ProfilesSampleRate: 1.0
Ristretto:
  NumCounters: 10
  MaxCost: 10000
  BufferItems: 32