// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/memnix/memnix/blob/main/PRIVACY.md",
        "contact": {
            "name": "API Support",
            "email": "contact@memnix.app"
        },
        "license": {
            "name": "BSD 3-Clause License",
            "url": "https://github.com/memnix/memnix-rest/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Login the user and return a fresh token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logins user and return a fresh token",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Incorrect password or email"
                    },
                    "500": {
                        "description": "Internal error"
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "Beaver": []
                    }
                ],
                "description": "Logout the user and create a record in the log",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logouts the user",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create a new user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "creates a new user",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "Beaver": []
                    }
                ],
                "description": "Get connected user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "gets connected user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseAuth"
                        }
                    },
                    "401": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/v1/cards/": {
            "get": {
                "description": "Get every card. Shouldn't really be used",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "gets all cards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Card"
                            }
                        }
                    }
                }
            }
        },
        "/v1/cards/deck/{deckID}": {
            "get": {
                "description": "Get every card from a deck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "gets a list of card",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Deck ID",
                        "name": "deckID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Card"
                            }
                        }
                    }
                }
            }
        },
        "/v1/cards/id/{id}": {
            "get": {
                "description": "Get a card by tech id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "gets a card",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Card ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Card"
                        }
                    }
                }
            }
        },
        "/v1/cards/new": {
            "post": {
                "description": "Create a new card",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "creates a card",
                "parameters": [
                    {
                        "description": "Card to create",
                        "name": "card",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Card"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/cards/response": {
            "post": {
                "description": "Post a response and check it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "posts a response",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/cards/selfresponse": {
            "post": {
                "description": "Post a self evaluated response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "posts a response",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/cards/today": {
            "get": {
                "description": "Get all today card",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "gets a list of card",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Card"
                            }
                        }
                    }
                }
            }
        },
        "/v1/cards/{cardID}": {
            "delete": {
                "description": "Delete a card",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "deletes a card",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/cards/{cardID}/edit": {
            "put": {
                "description": "Edit a card",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "edits a card",
                "parameters": [
                    {
                        "description": "card to edit",
                        "name": "card",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Card"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/cards/{deckID}/training": {
            "get": {
                "description": "Get training cards",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Card"
                ],
                "summary": "gets a list of cards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Card"
                            }
                        }
                    }
                }
            }
        },
        "/v1/decks": {
            "get": {
                "description": "Get every deck. Shouldn't really be used, consider using /v1/decks/public instead !",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "gets all decks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Deck"
                        }
                    }
                }
            }
        },
        "/v1/decks/available": {
            "get": {
                "description": "Get all public deck that you are not sub to",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "get a list of deck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ResponseDeck"
                            }
                        }
                    }
                }
            }
        },
        "/v1/decks/editor": {
            "get": {
                "description": "Get decks the user is an editor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "gets a list of deck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ResponseDeck"
                            }
                        }
                    }
                }
            }
        },
        "/v1/decks/new": {
            "post": {
                "description": "Create a new deck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "creates a deck",
                "parameters": [
                    {
                        "description": "Deck to create",
                        "name": "deck",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Deck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/private/{key}/{code}/subscribe": {
            "post": {
                "description": "Subscribe to a private deck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "sub deck",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/public": {
            "get": {
                "description": "Get all public deck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "gets a list of deck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Deck"
                            }
                        }
                    }
                }
            }
        },
        "/v1/decks/sub": {
            "get": {
                "description": "Get decks a user is sub to",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "gets a list of deck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ResponseDeck"
                            }
                        }
                    }
                }
            }
        },
        "/v1/decks/{deckID}": {
            "get": {
                "description": "Get a deck by tech ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "get a deck",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Deck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "model"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a deck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "delete a deck",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/{deckID}/edit": {
            "put": {
                "description": "Edit a deck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "edits a deck",
                "parameters": [
                    {
                        "description": "Deck to edit",
                        "name": "deck",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Deck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/{deckID}/publish": {
            "post": {
                "description": "Request to publish deck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "publishes a deck",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/{deckID}/subscribe": {
            "post": {
                "description": "Subscribe to a deck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "sub deck",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/{deckID}/unsubscribe": {
            "post": {
                "description": "Unsubscribe to a deck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "unsub deck",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/decks/{deckID}/users": {
            "get": {
                "description": "Get all the sub users to a deck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deck"
                ],
                "summary": "gets a list of users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            }
        },
        "/v1/mcqs/new": {
            "post": {
                "description": "Create a new mcq",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mcq"
                ],
                "summary": "creates a mcq",
                "parameters": [
                    {
                        "description": "Mcq to create",
                        "name": "mcq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Mcq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/mcqs/{deckID}": {
            "get": {
                "description": "Get mcqs linked to the deck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mcq"
                ],
                "summary": "gets a list of mcqs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Mcq"
                            }
                        }
                    }
                }
            }
        },
        "/v1/mcqs/{mcqID}": {
            "delete": {
                "description": "Delete a mcq",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mcq"
                ],
                "summary": "deletes a mcq",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/mcqs/{mcqID}/edit": {
            "put": {
                "description": "Edit a mcq",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mcq"
                ],
                "summary": "edits a mcq",
                "parameters": [
                    {
                        "description": "mcq to edit",
                        "name": "mcq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Mcq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "description": "Get all users.  Shouldn't really be used",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "gets a list of user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/v1/users/config/{deckId}/today": {
            "get": {
                "description": "Set the today config for a deck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "gets a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/v1/users/id/{id}": {
            "get": {
                "description": "Get a user by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "gets a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Card": {
            "type": "object",
            "properties": {
                "card_answer": {
                    "type": "string",
                    "example": "42"
                },
                "card_case": {
                    "type": "boolean"
                },
                "card_explication": {
                    "type": "string"
                },
                "card_explication_image": {
                    "type": "string"
                },
                "card_format": {
                    "type": "string",
                    "example": "Date / Name / Country"
                },
                "card_image": {
                    "description": "Should be an url",
                    "type": "string"
                },
                "card_question": {
                    "type": "string",
                    "example": "What's the answer to life ?"
                },
                "card_spaces": {
                    "type": "boolean"
                },
                "card_type": {
                    "type": "integer",
                    "example": 0
                },
                "deck": {
                    "$ref": "#/definitions/models.Deck"
                },
                "deck_id": {
                    "type": "integer",
                    "example": 1
                },
                "mcq": {
                    "$ref": "#/definitions/models.Mcq"
                }
            }
        },
        "models.Deck": {
            "type": "object",
            "properties": {
                "deck_banner": {
                    "type": "string",
                    "example": "A banner url"
                },
                "deck_code": {
                    "type": "string",
                    "example": "6452"
                },
                "deck_description": {
                    "type": "string",
                    "example": "A simple demo deck"
                },
                "deck_key": {
                    "type": "string",
                    "example": "MEM"
                },
                "deck_lang": {
                    "type": "string"
                },
                "deck_name": {
                    "type": "string",
                    "example": "First Deck"
                },
                "deck_share": {
                    "type": "boolean",
                    "example": true
                },
                "deck_status": {
                    "description": "1: Draft - 2: Private - 3: Published",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.LoginStruct": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Mcq": {
            "type": "object",
            "properties": {
                "deck": {
                    "$ref": "#/definitions/models.Deck"
                },
                "deck_id": {
                    "type": "integer",
                    "example": 1
                },
                "mcq_answers": {
                    "type": "string"
                },
                "mcq_name": {
                    "type": "string"
                },
                "mcq_type": {
                    "type": "integer"
                }
            }
        },
        "models.PublicUser": {
            "type": "object",
            "properties": {
                "user_avatar": {
                    "type": "string",
                    "example": "avatar url"
                },
                "user_bio": {
                    "type": "string",
                    "example": "A simple demo bio"
                },
                "user_name": {
                    "type": "string"
                },
                "user_permissions": {
                    "description": "0: User; 1: Mod; 2: Admin",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "models.RegisterStruct": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ResponseAuth": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.ResponseDeck": {
            "type": "object",
            "properties": {
                "card_count": {
                    "type": "integer",
                    "example": 42
                },
                "deck": {
                    "$ref": "#/definitions/models.Deck"
                },
                "deck_id": {
                    "type": "integer",
                    "example": 1
                },
                "owner": {
                    "$ref": "#/definitions/models.PublicUser"
                },
                "owner_id": {
                    "type": "integer",
                    "example": 6
                },
                "permission": {
                    "type": "integer",
                    "example": 1
                },
                "settings_today": {
                    "type": "boolean"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "user_avatar": {
                    "type": "string",
                    "example": "avatar url"
                },
                "user_bio": {
                    "type": "string",
                    "example": "A simple demo bio"
                },
                "user_name": {
                    "description": "This should be unique",
                    "type": "string",
                    "example": "Yume"
                },
                "user_permissions": {
                    "description": "0: User; 1: Mod; 2: Admin",
                    "type": "integer",
                    "example": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "Beaver": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "http://192.168.1.151:1813/",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "Memnix",
	Description: "Memnix API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
