name: Go

on:
  push:
    branches: [ "main", "v2", "develop" ]
  pull_request:
    branches: [ "main", "v2", "develop"]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
