name: Go

on:
  push:
    branches: [ "main", "v2", "develop" ]
  pull_request:
    branches: [ "main", "v2", "develop"]

jobs:
  # Check if there is any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
